# Generated by Django 5.2.14 on 2026-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_title_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
